[default.probe]
protocol = "Swd"

[default.flashing]
enabled = false
halt_afterwards = false
restore_unwritten_bytes = false

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "nRF51822_xxAC"
chip_descriptions = []
log_level = "WARN"

[default.rtt]
enabled = true
channels = []
timeout = 3000
show_timestamps = true
log_enabled = false
log_path = "./logs"

[default.gdb]
enabled = false

# Profile for flashing.
[flash.flashing]
enabled = true
